---
title: Flipside
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"
    Main Image: 
    description:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: category
  values:
    layout: category
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
url:
markdown: kramdown
_postcollections:
  category:
    title: Category
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
